# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 20:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u83dc\u5355\u540d\u79f0')),
                ('code', models.CharField(max_length=20, verbose_name='\u83dc\u5355\u4ee3\u7801')),
                ('is_leaf', models.BooleanField(default=False, verbose_name='\u662f\u5426\u4e3a\u5b50\u8282\u70b9')),
                ('linkto', models.CharField(default='#', max_length=50, verbose_name='\u94fe\u63a5\u5730\u5740')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('parent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='management.Menu')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
