# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20170703_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='users',
        ),
        migrations.AddField(
            model_name='user',
            name='menus',
            field=models.ManyToManyField(to='management.Menu', verbose_name='\u7528\u6237\u83dc\u5355'),
        ),
    ]
