# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20170703_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='management.Menu', verbose_name='\u7236\u83dc\u5355'),
        ),
    ]
