# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20170703_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='menus',
            field=models.ManyToManyField(blank=True, to='management.Menu', verbose_name='\u7528\u6237\u83dc\u5355'),
        ),
    ]
