# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20170709_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verbose_name',
            field=models.CharField(default='', max_length=50, verbose_name='\u663e\u793a\u540d\u79f0'),
        ),
    ]
