# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_ptr',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
