# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_auto_20170715_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u5b57\u6bb5\u540d\u79f0')),
                ('verbose_name', models.CharField(max_length=50, verbose_name='\u5b57\u6bb5\u663e\u793a\u540d\u79f0')),
                ('ordered', models.IntegerField(verbose_name='\u987a\u5e8f')),
                ('is_pk', models.BooleanField(default=False, verbose_name='\u662f\u5426\u662f\u4e3b\u952e')),
            ],
        ),
        migrations.CreateModel(
            name='ColumnType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u5b57\u6bb5\u7c7b\u578b')),
                ('verbose_name', models.CharField(max_length=50, verbose_name='\u5b57\u6bb5\u7c7b\u578b\u663e\u793a\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u6570\u636e\u5e93\u540d\u79f0')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u8868\u540d\u79f0')),
                ('verbose_name', models.CharField(max_length=50, verbose_name='\u8868\u663e\u793a\u540d\u79f0')),
                ('field_separator', models.CharField(default=',', max_length=20, verbose_name='\u5217\u5206\u9694\u7b26')),
                ('record_separator', models.CharField(default='\\n', max_length=20, verbose_name='\u884c\u5206\u9694\u7b26')),
                ('quote_character', models.CharField(default='"', max_length=20, verbose_name='\u62ec\u8d77\u5185\u5bb9\u5b57\u7b26')),
                ('location', models.CharField(default='', max_length=200, verbose_name='\u8868\u5185\u5bb9\u6587\u4ef6\u5b58\u50a8\u4f4d\u7f6e')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
        ),
        migrations.AddField(
            model_name='column',
            name='column_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.ColumnType', verbose_name='\u5b57\u6bb5\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='column',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Table', verbose_name='\u8868'),
        ),
    ]
