# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=50, verbose_name='\u4efb\u52a1\u540d\u79f0')),
                ('job_type', models.CharField(max_length=50, verbose_name='\u4efb\u52a1\u7c7b\u578b')),
                ('data_source', models.CharField(max_length=200, verbose_name='\u6570\u636e\u6e90')),
                ('destination', models.CharField(max_length=200, verbose_name='\u76ee\u7684\u5730')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('interval', models.CharField(default='', max_length=50, verbose_name='\u91c7\u96c6\u95f4\u9694')),
                ('next_time', models.DateTimeField(verbose_name='\u4e0b\u6b21\u91c7\u96c6\u65f6\u95f4')),
                ('pid', models.CharField(default='', max_length=50, verbose_name='\u6267\u884c\u91c7\u96c6\u4efb\u52a1\u8fdb\u7a0b\u53f7')),
                ('status', models.CharField(default='NO_RUN', max_length=50, verbose_name='\u72b6\u6001')),
            ],
            options={
                'ordering': ('-modified',),
            },
        ),
    ]
