# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_scrapejobdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapejobdetail',
            name='error_messages',
            field=models.TextField(default='', verbose_name='\u9519\u8bef\u4fe1\u606f'),
        ),
    ]
