# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 08:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(default='', verbose_name='\u67e5\u8be2\u5185\u5bb9')),
                ('excuted_query', models.TextField(default='', verbose_name='\u6267\u884c\u7684\u67e5\u8be2')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('duration', models.FloatField(default=0.0, verbose_name='\u6267\u884c\u65f6\u957f')),
                ('total', models.IntegerField(default=0, verbose_name='\u67e5\u8be2\u7ed3\u679c\u6570\u91cf')),
                ('error_messages', models.TextField(default='', verbose_name='\u67e5\u8be2\u9519\u8bef')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6267\u884c\u4eba')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
