# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='error_messages',
            field=models.TextField(blank=True, default='', verbose_name='\u67e5\u8be2\u9519\u8bef'),
        ),
    ]
