# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0005_auto_20170619_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='excuted_query',
            new_name='executed_query',
        ),
        migrations.RenameField(
            model_name='query',
            old_name='total',
            new_name='rows',
        ),
    ]
