# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0006_auto_20170621_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='page_number',
            field=models.IntegerField(default=0, verbose_name='\u9875\u6570'),
        ),
    ]
