# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0009_auto_20170715_0303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='query',
            options={'ordering': ('-created',)},
        ),
    ]
